### PR TITLE
Add GitHub Action to produce all artifacts

### PR DESCRIPTION
**Pull request by chris-allan**
Updates the build process to handle all steps using GitHub Actions:

 * Build of Win64 native artifact
 * Build of Linux64 native artifact
 * Build of macOS native artifact
 * Combination build of Java outputs and native artifacts from all 3 platforms

Of note:

 * Builds of the Win64 native artifact are now being performed by VS2019. This should mean a new dependency on the VC 2019 C++ redistributable on Windows. (Needs validation)
 * Builds of the Linux64 native artifact are being performed using the manylinux2010 infrastructure from PyPA. This should preserve CentOS 6 compatibility.
 * Builds of the macOS native artifact are now being performed using XCode 11.3.2. macOS version compatibility will need to be validated.

/cc @sbesson, @jburel

### CODE REVIEW

**Comment by chris-allan** [comment]
@stick: We will need to validate where we have still have access to CentOS 6.

**Comment by melissalinkert** [comment]
Minimal test: https://gist.github.com/melissalinkert/500944d2215902b11502b8b726a41c18

Run ```javac -cp jxrlib-all-0.2.4.jar:. JXRTest.java```, then ```java JXRTest img6_lowest_res.jxr``` with an appropriate runtime classpath. The test file is in ```s3://bf-data-repo/jpegxr-test/```.  Runtime classpath will require:

* jxrlib-all-0.2.4.jar
* logback-classic.jar
* logback-core.jar
* native-lib-loader.jar
* slf4j-api.jar
* working directory

All jars except ```jxrlib-all-0.2.4.jar``` are zipped in ```s3://bf-data-repo/jpegxr-test/jars.zip```

**Comment by stick** [comment]
tested on centos6:

```
12:30:58.759 [main] DEBUG o.s.nativelib.NativeLibraryUtil - processor is INTEL_64 os.arch is amd64
12:30:58.760 [main] DEBUG o.s.nativelib.NativeLibraryUtil - architecture is LINUX_64 os.name is linux
12:30:58.769 [main] DEBUG o.s.nativelib.NativeLibraryUtil - architecture is LINUX_64 os.name is linux
12:30:58.769 [main] DEBUG o.s.nativelib.NativeLibraryUtil - platform specific path is META-INF/lib/linux_64/
12:30:58.769 [main] DEBUG o.scijava.nativelib.BaseJniExtractor - mappedLib is libjxrjava.so
12:30:58.769 [main] DEBUG o.scijava.nativelib.BaseJniExtractor - URL is jar:file:/home/cm298/jxr-test/jxrlib-all-0.2.4.jar!/META-INF/lib/linux_64/libjxrjava.so
12:30:58.769 [main] DEBUG o.scijava.nativelib.BaseJniExtractor - URL path is file:/home/cm298/jxr-test/jxrlib-all-0.2.4.jar!/META-INF/lib/linux_64/libjxrjava.so
12:30:58.777 [main] DEBUG o.scijava.nativelib.BaseJniExtractor - Extracting 'jar:file:/home/cm298/jxr-test/jxrlib-all-0.2.4.jar!/META-INF/lib/linux_64/libjxrjava.so' to '/tmp/libjxrjava12900523056665113279.so'
bytes per pixel = 3
BGR = false
```

**Review by stick — APPROVED** [review]

**Review by melissalinkert — APPROVED** [review]

**Comment by melissalinkert** [comment]
Closing as discussed in the context of upcoming work on #32.

**Pull request closed without merging**
